"""Worked ECC examples on the toy curve from the PKI volume.

Everything in the PKI volume's mathematics sections, computed rather than
asserted. Run it and every number in the text appears in the output.

    python3 ecc_worked_examples.py

The curve is y^2 = x^3 + 2x + 2 (mod 17), G = (5, 1), n = 19. It is far too
small to be secure - that is the point. Numbers you can follow by hand teach
the mechanism; P-256 teaches nothing you can see.

Sections:
  1. The curve and its group
  2. Key generation
  3. ECDH - both sides reach the same secret
  4. ECDSA - sign and verify
  5. Nonce reuse recovers the private key
  6. Why an invalid-curve check matters
"""

P, A, B = 17, 2, 2
G = (5, 1)
N = 19                      # order of G, verified in section 1


# --- field and curve arithmetic ------------------------------------------

def inv(x):
    """Modular inverse. P is prime, so Fermat's little theorem suffices."""
    return pow(x % P, P - 2, P)


def on_curve(pt):
    if pt is None:
        return True
    x, y = pt
    return (y * y - (x ** 3 + A * x + B)) % P == 0


def add(p1, p2):
    """Point addition, including the doubling case.

    Doubling uses the tangent slope, which is implicit differentiation of
    the curve equation:  2y dy/dx = 3x^2 + a  ->  lam = (3x^2 + a) / 2y.
    Ordinary addition uses the chord slope (y2 - y1) / (x2 - x1).
    """
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    if p1[0] == p2[0] and (p1[1] + p2[1]) % P == 0:
        return None                                   # vertical line
    if p1 == p2:
        lam = (3 * p1[0] * p1[0] + A) * inv(2 * p1[1]) % P
    else:
        lam = (p2[1] - p1[1]) * inv(p2[0] - p1[0]) % P
    x3 = (lam * lam - p1[0] - p2[0]) % P
    y3 = (lam * (p1[0] - x3) - p1[1]) % P
    return (x3, y3)


def mul(k, pt):
    """Scalar multiplication by double-and-add.

    NOTE: this is the textbook version and it is NOT constant time - the
    branch on the key bit is exactly the leak a timing or power side channel
    exploits. A real implementation uses a Montgomery ladder or equivalent.
    """
    result, addend = None, pt
    while k:
        if k & 1:
            result = add(result, addend)
        addend = add(addend, addend)
        k >>= 1
    return result


def show(pt):
    return 'O (infinity)' if pt is None else str(pt)


def rule(title):
    print(f'\n{"=" * 66}\n{title}\n{"=" * 66}')


# --- 1. the curve ---------------------------------------------------------

def section_curve():
    rule('1. The curve and its group')
    print(f'  y^2 = x^3 + {A}x + {B}  (mod {P})        G = {G}')
    assert on_curve(G), 'G is not on the curve'
    print(f'  G satisfies the curve equation: {G[1]}^2 = {G[1]**2 % P}, '
          f'{G[0]}^3 + {A}*{G[0]} + {B} = {(G[0]**3 + A*G[0] + B) % P}  (mod {P})')

    print('\n  The subgroup generated by G:')
    pt, order = G, None
    for i in range(1, 30):
        print(f'    {i:2d}G = {show(pt)}')
        if pt is None:
            order = i
            break
        pt = add(pt, G)
    assert order == N, f'expected order {N}, got {order}'
    print(f'\n  Order of G is {order}. Private keys live in [1, {N - 1}].')
    print(f'  That is {N - 1} possible keys - trivially brute-forced, which is')
    print('  why this curve is only ever a teaching aid.')


# --- 2. key generation ----------------------------------------------------

def section_keygen():
    rule('2. Key generation:  Q = d * G')
    for d in (7, 3, 12):
        q = mul(d, G)
        assert on_curve(q)
        print(f'  d = {d:2d}   ->   Q = {d}G = {show(q)}')
    print('\n  Easy forwards. Recovering d from Q is the elliptic curve')
    print('  discrete logarithm problem - here you could just try all 18.')


# --- 3. ECDH --------------------------------------------------------------

def section_ecdh():
    rule('3. ECDH - two parties, one shared secret')
    dA, dB = 7, 11
    QA, QB = mul(dA, G), mul(dB, G)
    print(f'  Endpoint A: private dA = {dA}   public QA = {show(QA)}')
    print(f'  Endpoint B: private dB = {dB}   public QB = {show(QB)}')
    print('\n  QA and QB travel over the wire in the clear.\n')
    zA, zB = mul(dA, QB), mul(dB, QA)
    print(f'  A computes Z = dA * QB = {show(zA)}')
    print(f'  B computes Z = dB * QA = {show(zB)}')
    assert zA == zB
    print(f'\n  Identical, because dA*(dB*G) = dB*(dA*G) = {dA * dB}G.')
    print('  An eavesdropper has G, QA and QB, and still cannot get Z')
    print('  without solving the discrete log.')
    print('\n  Z is NOT the key. Z is input to a KDF, which produces keys of the')
    print('  right length, separated by purpose. Using Z directly as an AES key')
    print('  is a real and recurring implementation mistake.')


# --- 4. ECDSA -------------------------------------------------------------

def sign(d, e, k):
    """One ECDSA signature. e is the message hash reduced mod N."""
    R = mul(k, G)
    r = R[0] % N
    s = inv_n(k) * (e + r * d) % N
    assert r and s, 'degenerate signature - pick another k'
    return r, s


def inv_n(x):
    return pow(x % N, N - 2, N)          # N is prime here


def verify(Q, e, sig):
    r, s = sig
    if not (1 <= r < N and 1 <= s < N):
        return False
    w = inv_n(s)
    u1, u2 = e * w % N, r * w % N
    X = add(mul(u1, G), mul(u2, Q))
    return X is not None and X[0] % N == r


def section_ecdsa():
    rule('4. ECDSA - sign and verify')
    d = 7
    Q = mul(d, G)
    # e stands in for Hash(M) reduced mod n. Not every (e, k) pair is
    # usable: on this curve k = 5 gives r = 9, and s = 4(e + 6) mod 19,
    # which is zero exactly when e = 13. A real signer retries with a new k.
    e = 11
    k = 5
    print(f'  private d = {d}   public Q = {show(Q)}')
    print(f'  message hash e = {e}   per-signature nonce k = {k}')
    r, s = sign(d, e, k)
    print(f'\n  R = kG = {show(mul(k, G))}')
    print(f'  r = R.x mod n         = {r}')
    print(f'  s = k^-1 (e + r d)    = {s}')
    print(f'  signature = ({r}, {s})')
    ok = verify(Q, e, (r, s))
    print(f'\n  verify with Q      -> {ok}')
    assert ok
    bad = verify(Q, (e + 1) % N, (r, s))
    print(f'  verify with e+1    -> {bad}   (message changed, signature fails)')
    assert not bad
    other = verify(mul(3, G), e, (r, s))
    print(f'  verify with wrong Q-> {other}   (different key, signature fails)')
    assert not other


# --- 5. the nonce catastrophe --------------------------------------------

def section_nonce_reuse():
    rule('5. Reusing k recovers the private key')
    d, k = 7, 5
    Q = mul(d, G)
    e1, e2 = 11, 4
    r1, s1 = sign(d, e1, k)
    r2, s2 = sign(d, e2, k)

    print(f'  The signer reuses k = {k} for two different messages.\n')
    print(f'    message 1: e1 = {e1}   signature = ({r1}, {s1})')
    print(f'    message 2: e2 = {e2}   signature = ({r2}, {s2})')
    print(f'\n  First tell: r1 == r2 == {r1}. r depends only on k, so an equal r')
    print('  across two signatures is a public, visible advertisement of reuse.')

    print('\n  The attacker now has two equations:')
    print('      s1 = k^-1 (e1 + r d)')
    print('      s2 = k^-1 (e2 + r d)')
    print('  Subtracting eliminates d:   s1 - s2 = k^-1 (e1 - e2)')
    k_rec = (e1 - e2) * inv_n(s1 - s2) % N
    print(f'\n      k = (e1 - e2) / (s1 - s2) mod n = {k_rec}')
    assert k_rec == k
    d_rec = (s1 * k_rec - e1) * inv_n(r1) % N
    print(f'      d = (s1 k - e1) / r     mod n = {d_rec}')
    assert d_rec == d
    print(f'\n  Recovered private key = {d_rec}. The real one was {d}.')
    print('\n  This is arithmetic, not cryptanalysis. It works identically on')
    print('  P-256 and it has cost real systems their signing keys. The defence')
    print('  is a CSPRNG seeded from real entropy, or deterministic ECDSA')
    print('  (RFC 6979), which derives k from the private key and the message.')


# --- 6. invalid curve points ---------------------------------------------

def section_invalid_point():
    rule('6. Validate every public key you receive')
    print('  An attacker sends a "public key" that is not on the curve:')
    fake = (5, 2)
    print(f'    claimed point {fake}: on the curve? {on_curve(fake)}')
    print('\n  Multiplying your private key by an off-curve point leaks')
    print('  information about that key - the invalid-curve attack. Every')
    print('  received point must be checked: on the curve, not the point at')
    print('  infinity, in the correct subgroup.')
    print('\n  Certificate validation does not replace this check. A valid')
    print('  signature over a malformed point still yields a malformed point.')


if __name__ == '__main__':
    section_curve()
    section_keygen()
    section_ecdh()
    section_ecdsa()
    section_nonce_reuse()
    section_invalid_point()
    print('\n' + '=' * 66)
    print('All assertions passed.')
    print('=' * 66)
